stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw
      - src/preprocess.py

  train:
    cmd: python src/train.py
    deps:
      - data/processed
      - src/train.py
      - params.yaml

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.h5
      - data/processed
      - src/evaluate.py
    metrics:
      - metrics.json